SET NAMES utf8;
SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS `cd_adweixin`;
CREATE TABLE `cd_adweixin` ( `id` bigint(19) unsigned NOT NULL AUTO_INCREMENT, `user_id` bigint(19) unsigned NOT NULL DEFAULT '0', `original_wxid` varchar(20) NOT NULL DEFAULT '', `custom_wxid` varchar(50) NOT NULL DEFAULT '', `wxname` varchar(50) NOT NULL DEFAULT '', `avatar` varchar(250) NOT NULL DEFAULT '', `contact` varchar(20) NOT NULL DEFAULT '', `phone` varchar(20) NOT NULL DEFAULT '', `qq` varchar(20) NOT NULL DEFAULT '', `email` varchar(250) NOT NULL DEFAULT '', `site` varchar(250) NOT NULL DEFAULT '', `create_time` bigint(20) NOT NULL DEFAULT '0', `create_ip` varchar(15) NOT NULL DEFAULT '', `desc` text, `state` tinyint(3) unsigned NOT NULL DEFAULT '0', PRIMARY KEY (`id`), KEY `user_id_idx` (`user_id`), KEY `state_idx` (`state`), KEY `create_time_idx` (`create_time`)) ENGINE=MyISAM AUTO_INCREMENT=10 DEFAULT CHARSET=utf8;
DROP TABLE IF EXISTS `cd_comment`;
CREATE TABLE `cd_comment` ( `id` bigint(19) unsigned NOT NULL AUTO_INCREMENT, `post_id` bigint(19) unsigned NOT NULL DEFAULT '0', `content` text, `user_id` bigint(19) unsigned NOT NULL DEFAULT '0', `user_name` varchar(50) NOT NULL DEFAULT '', `create_time` int(11) NOT NULL DEFAULT '0', `create_ip` varchar(15) NOT NULL DEFAULT '', `up_score` int(10) unsigned NOT NULL DEFAULT '0', `down_score` int(10) unsigned NOT NULL DEFAULT '0', `state` tinyint(3) unsigned NOT NULL DEFAULT '0', PRIMARY KEY (`id`), KEY `post_id_state_create_time_idx` (`post_id`,`state`,`create_time`), KEY `user_id_create_time_idx` (`user_id`,`create_time`), KEY `state_idx` (`state`), KEY `create_time_idx` (`create_time`)) ENGINE=MyISAM AUTO_INCREMENT=13 DEFAULT CHARSET=utf8;
DROP TABLE IF EXISTS `cd_config`;
CREATE TABLE `cd_config` ( `id` bigint(19) unsigned NOT NULL AUTO_INCREMENT, `category_id` bigint(19) unsigned NOT NULL DEFAULT '0', `config_name` varchar(100) NOT NULL DEFAULT '', `config_value` text, `name` varchar(50) NOT NULL DEFAULT '', `desc` text, PRIMARY KEY (`id`), UNIQUE KEY `config_name_UNIQUE` (`config_name`), KEY `category_id_id_idx` (`category_id`,`id`)) ENGINE=MyISAM AUTO_INCREMENT=4 DEFAULT CHARSET=utf8 COMMENT='配置信息表';
DROP TABLE IF EXISTS `cd_post`;
CREATE TABLE `cd_post` (`id` bigint(19) unsigned NOT NULL AUTO_INCREMENT,  `weixin_id` bigint(19) unsigned NOT NULL DEFAULT '0',  `user_id` bigint(19) unsigned NOT NULL DEFAULT '0',  `title` varchar(200) NOT NULL DEFAULT '',  `content` text,  `theme_name` varchar(50) NOT NULL DEFAULT '',  `view_count` bigint(19) unsigned NOT NULL DEFAULT '0',  `back_count` bigint(19) unsigned NOT NULL DEFAULT '0',  `share_count` bigint(19) unsigned NOT NULL DEFAULT '0',  `comment_count` int(10) unsigned NOT NULL DEFAULT '0',  `create_time` int(10) unsigned NOT NULL DEFAULT '0',  `create_ip` varchar(15) NOT NULL DEFAULT '',  `ad_accounts` text,  `ad_line_count` tinyint(4) NOT NULL DEFAULT '0',  PRIMARY KEY (`id`),  KEY `weixin_id` (`weixin_id`),  KEY `user_id` (`user_id`),  KEY `create_time` (`create_time`)) ENGINE=MyISAM DEFAULT CHARSET=utf8
DROP TABLE IF EXISTS `cd_post_weixin`;
CREATE TABLE `cd_post_weixin` ( `id` bigint(19) unsigned NOT NULL AUTO_INCREMENT, `post_id` bigint(19) unsigned NOT NULL DEFAULT '0', `wx_id` bigint(19) unsigned NOT NULL DEFAULT '0', `follow_success` bigint(19) unsigned NOT NULL DEFAULT '0', `follow_fail` bigint(19) unsigned NOT NULL DEFAULT '0', PRIMARY KEY (`id`), KEY `post_id_idx` (`post_id`)) ENGINE=MyISAM AUTO_INCREMENT=14 DEFAULT CHARSET=utf8;
DROP TABLE IF EXISTS `cd_user`;
CREATE TABLE `cd_user` ( `id` bigint(19) unsigned NOT NULL AUTO_INCREMENT, `email` varchar(100) NOT NULL DEFAULT '', `name` varchar(50) NOT NULL DEFAULT '', `password` varchar(32) NOT NULL DEFAULT '', `create_time` int(11) NOT NULL DEFAULT '0', `create_ip` varchar(15) NOT NULL DEFAULT '', `state` tinyint(4) NOT NULL DEFAULT '0', `token` varchar(32) NOT NULL DEFAULT '', PRIMARY KEY (`id`), UNIQUE KEY `email_UNIQUE` (`email`), UNIQUE KEY `name_UNIQUE` (`name`), KEY `state_id_idx` (`state`,`id`), KEY `create_time_idx` (`create_time`)) ENGINE=MyISAM AUTO_INCREMENT=4 DEFAULT CHARSET=utf8;
DROP TABLE IF EXISTS `cd_weixin`;
CREATE TABLE `cd_weixin` ( `id` bigint(19) unsigned NOT NULL AUTO_INCREMENT, `user_id` bigint(19) unsigned NOT NULL DEFAULT '0', `original_wxid` varchar(20) NOT NULL DEFAULT '', `custom_wxid` varchar(50) NOT NULL DEFAULT '', `wxname` varchar(50) NOT NULL DEFAULT '', `rect_avatar` varchar(250) NOT NULL DEFAULT '', `circle_avatar` varchar(250) NOT NULL DEFAULT '', `qrcode` varchar(250) NOT NULL DEFAULT '', `fans_count` bigint(20) NOT NULL DEFAULT '0', `contact` varchar(20) NOT NULL DEFAULT '', `phone` varchar(20) NOT NULL DEFAULT '', `qq` varchar(20) NOT NULL DEFAULT '', `email` varchar(250) NOT NULL DEFAULT '', `site` varchar(250) NOT NULL DEFAULT '', `tags` varchar(250) NOT NULL DEFAULT '', `post_count` int(11) NOT NULL DEFAULT '0', `create_time` bigint(20) NOT NULL DEFAULT '0', `create_ip` varchar(15) NOT NULL DEFAULT '', `desc` text, `state` tinyint(4) NOT NULL DEFAULT '0', PRIMARY KEY (`id`), KEY `user_id` (`user_id`), KEY `state` (`state`), KEY `create_time` (`create_time`), KEY `user_id_original_wxid_unique` (`user_id`,`original_wxid`)) ENGINE=MyISAM AUTO_INCREMENT=13 DEFAULT CHARSET=utf8;

INSERT INTO `cd_config` VALUES ('1', '200', 'theme_name', 'classic', '模板', null), ('2', '100', 'site_name', '挖段子冷笑话2', '站点名称', null), ('3', '100', 'shortdesc', '挖段子网1', '站点描述', null);
INSERT INTO `cd_user` VALUES ('1', 'admin@24beta.com', '微800', '4297f44b13955235245b2497399d7a93', '0', '', '1', '');
SET FOREIGN_KEY_CHECKS = 1;
